"""Public contracts for scheduler-callable vfWorks actions.

This package deliberately depends only on the Python standard library. External
workflow engines can import these contracts without importing the vfWorks GUI,
machine-learning backends, or internal workflow executor.
"""

from vfworks.actions.contracts import (
    ArtifactRef,
    ExecutionInfo,
    JSONPrimitive,
    JSONValue,
)
from vfworks.actions.data import (
    CollectedRows,
    TabularArtifactStore,
    TabularDataCollector,
    TabularRow,
    collect_data,
    prepare_data,
)
from vfworks.actions.exceptions import (
    ArtifactIntegrityError,
    ArtifactNotFound,
    BackendUnavailable,
    DataPreparationError,
    InvalidActionInput,
    ModelEvaluationError,
    ModelTrainingError,
    VFWorksActionError,
    ValidityFrameExportError,
)
from vfworks.actions.models import (
    BackendEvaluateRequest,
    BackendFitRequest,
    CollectDataRequest,
    CollectDataResult,
    EvaluateModelRequest,
    EvaluateModelResult,
    ExportValidityFrameRequest,
    ExportValidityFrameResult,
    FitModelRequest,
    FitModelResult,
    FittedModel,
    LoadModelRequest,
    LoadModelResult,
    ModelArtifactStore,
    ModelBackend,
    ModelDocumentStore,
    ModelEvaluation,
    ModelEvaluator,
    PostprocessModelRequest,
    PostprocessModelResult,
    PrepareDataRequest,
    PrepareDataResult,
    TrainingDatasetStore,
    evaluate_model,
    fit_model,
)
from vfworks.actions.protocols import ActionProvider
from vfworks.actions.registry import (
    ACTION_CONTRACT_VERSION,
    ActionDefinition,
    ActionRegistry,
    default_action_registry,
    get_action_definition,
)

__all__ = [
    "ACTION_CONTRACT_VERSION",
    "ArtifactIntegrityError",
    "ArtifactNotFound",
    "ArtifactRef",
    "ActionProvider",
    "ActionDefinition",
    "ActionRegistry",
    "BackendEvaluateRequest",
    "BackendFitRequest",
    "BackendUnavailable",
    "CollectDataRequest",
    "CollectDataResult",
    "CollectedRows",
    "DataPreparationError",
    "EvaluateModelRequest",
    "EvaluateModelResult",
    "ExecutionInfo",
    "ExportValidityFrameRequest",
    "ExportValidityFrameResult",
    "FitModelRequest",
    "FitModelResult",
    "FittedModel",
    "InvalidActionInput",
    "JSONPrimitive",
    "JSONValue",
    "ModelEvaluationError",
    "ModelTrainingError",
    "ModelArtifactStore",
    "ModelBackend",
    "ModelDocumentStore",
    "ModelEvaluation",
    "ModelEvaluator",
    "LoadModelRequest",
    "LoadModelResult",
    "PostprocessModelRequest",
    "PostprocessModelResult",
    "PrepareDataRequest",
    "PrepareDataResult",
    "TabularArtifactStore",
    "TabularDataCollector",
    "TabularRow",
    "TrainingDatasetStore",
    "VFWorksActionError",
    "ValidityFrameExportError",
    "collect_data",
    "default_action_registry",
    "evaluate_model",
    "fit_model",
    "get_action_definition",
    "prepare_data",
]
